"""Tests for the bundled pricing snapshot + sync_bundled_pricing().

The bundle ships inside the somm-core wheel (data/pricing_bundle.json,
generated by scripts/update_pricing_bundle.py from LiteLLM's price file)
so cost tracking works offline for every provider somm routes to.
"""

from __future__ import annotations

import json
from importlib import resources
from pathlib import Path
from tempfile import TemporaryDirectory

from somm_core.pricing import (
    cost_for_call,
    seed_known_pricing,
    sync_bundled_pricing,
    write_intel,
)
from somm_core.repository import Repository


def _fresh_repo() -> tuple[Repository, TemporaryDirectory]:
    tmpdir = TemporaryDirectory()
    return Repository(Path(tmpdir.name) / "test.db"), tmpdir


def _intel_row(repo, provider, model):
    with repo._open() as conn:
        return conn.execute(
            "SELECT price_in_per_1m, price_out_per_1m, source FROM model_intel "
            "WHERE provider=? AND model=?",
            (provider, model),
        ).fetchone()


def test_bundle_file_ships_and_parses():
    data = (resources.files("somm_core") / "data" / "pricing_bundle.json").read_bytes()
    bundle = json.loads(data)
    assert len(bundle["models"]) > 200
    providers = {m["provider"] for m in bundle["models"]}
    # Every paid provider somm routes to must be covered.
    assert {"anthropic", "openai", "gemini", "deepseek", "minimax", "perplexity"} <= providers


def test_sync_fills_previously_unpriced_providers():
    repo, _tmp = _fresh_repo()
    seed_known_pricing(repo)  # old seed has no gemini/deepseek rows
    written = sync_bundled_pricing(repo)
    assert written > 200
    for provider, model in [
        ("gemini", "gemini-2.5-pro"),
        ("deepseek", "deepseek-chat"),
        ("minimax", "MiniMax-M2.7"),
        ("perplexity", "sonar"),
    ]:
        row = _intel_row(repo, provider, model)
        assert row is not None, f"{provider}/{model} missing after sync"
        assert row[0] > 0, f"{provider}/{model} has zero input price"
        assert row[2] == "litellm_bundle"
    # And cost actually computes now.
    assert cost_for_call(repo, "gemini", "gemini-2.5-pro", 1000, 1000) > 0


def test_sync_updates_stale_seed_rows_but_not_manual_ones():
    repo, _tmp = _fresh_repo()
    seed_known_pricing(repo)
    write_intel(
        repo, provider="anthropic", model="claude-opus-4-7",
        price_in_per_1m=99.0, price_out_per_1m=99.0,
        context_window=None, capabilities=None, source="manual",
    )
    sync_bundled_pricing(repo)
    # seed row updated by the bundle
    row = _intel_row(repo, "anthropic", "claude-haiku-4-5-20251001")
    assert row[2] == "litellm_bundle"
    # manual row untouched
    row = _intel_row(repo, "anthropic", "claude-opus-4-7")
    assert row[:2] == (99.0, 99.0)
    assert row[2] == "manual"


def test_sync_is_idempotent_and_cheap_on_second_call():
    repo, _tmp = _fresh_repo()
    assert sync_bundled_pricing(repo) > 0
    assert sync_bundled_pricing(repo) == 0  # fingerprint match → no-op
